publisher_joint_trajectory_controller:
  ros__parameters:

    controller_name: "joint_trajectory_controller"
    wait_sec_between_publish: 10

    goal_names: ["pos1", "pos2"]
    pos1:
      positions: [0.0, 0.2, 0.0, 0.0]
    pos2:
      positions: [0.1, 0.22, 0.0, 0.0]

    joints:
      - j1
      - j2
      - j3
      - j4

    check_starting_point: false
